SETTINGS:
#The plugin's prefix for messages. Don't forget to leave a space at the end :)
  plugin_header: "ยง6[MysticLevels]: "
#Does events gives xp ? You can disable this per-skill too ;)
  give_xp: true
#Does events gives money ? You can disable this per-skill too ;)
  give_money: false