name: MysticLevels
author: Choco70
main: fr.choco70.mysticlevels.MysticLevels
version: 1.1.2
api-version: "1.14"
softdepend: [Vault, PlaceholderAPI]
commands:
  skills:
    description: View all skills commands.
    usage: /skills [subcommand]